version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "defects"
      POSTGRES_USER: "defect_bot"
      POSTGRES_PASSWORD: "zadolbalas"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - defects-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  defects-data: