version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    #env_file: .env  # Подгружаем переменные окружения (пароли, логины)
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./data.csv:/docker-entrypoint-initdb.d/data.csv
    networks:
      - bot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 13s
      timeout: 5s
      retries: 5
      start_period: 10s

  bot:
    build: .
    container_name: defects_bot
    restart: always
    #env_file: .env  # Подключаем переменные окружения
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - TYPE=${TYPE}
      - PROJECT_ID=${PROJECT_ID}
      - PRIVATE_KEY_ID=${PRIVATE_KEY_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CLIENT_EMAIL=${CLIENT_EMAIL}
      - CLIENT_ID=${CLIENT_ID}
      - AUTH_URI=${AUTH_URI}
      - TOKEN_URI=${TOKEN_URI}
      - AUTH_PROVIDER_X509_CERT_URL=${AUTH_PROVIDER_X509_CERT_URL}
      - CLIENT_X509_CERT_URL=${CLIENT_X509_CERT_URL}
      - UNIVERSE_DOMAIN=${UNIVERSE_DOMAIN}
    depends_on:
      - db
    networks:
      - bot_network
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    container_name: fastapi_service
    restart: always
    #env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - bot_network

volumes:
  pgdata:  #по умолчанию сейчас

networks:
  bot_network:  # Общая сеть для бота и базы
    driver: bridge